export const STARTED_LOADING_DATA = 'STARTED_LOADING_DATA';
export const FINISHED_LOADING_DATA = 'FINISHED_LOADING_DATA';
export const ERROR_LOADING_DATA = 'ERROR_LOADING_DATA';
export const STARTED_SEARCH_DATA = 'STARTED_SEARCH_DATA';
export const FINISHED_SEARCH_DATA = 'FINISHED_SEARCH_DATA';
export const ERROR_SEARCHING_DATA = 'ERROR_SEARCHING_DATA';