export const OPEN_MODAL="OPEN_MODAL";
export const CLOSE_MODAL="CLOSE_MODAL";
export const FINISHED_OPEN_MODEL='FINISHED_OPEN_MODEL';
export const ERROR_LOADING_DETAILS_MOVIE='ERROR_LOADING_DETAILS_MOVIE';
export const ERROR_LOADING_DETAILS_TV='ERROR_LOADING_DETAILS_TV';