export const SET_YEAR = 'SET_YEAR';
export const SET_GENRE = 'SET_GENRE';
export const STARTED_LOADING_GENRES = 'STARTED_LOADING_GENRES';
export const FINISHED_LOADING_GENRES = 'FINISHED_LOADING_GENRES';
export const ERROR_LOADING_GENRES = 'ERROR_LOADING_GENRES';